version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: EXAMPLE_PASSWORD
      REDMINE_SECRET_KEY_BASE: EXAMPLE_SUPERSECRETTKEY

  db:
    image: mysql:8.4.2
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_database

