service:
  ## @param service.type WordPress service type
  ##
  type: ClusterIP
  ## @param service.ports.http WordPress service HTTP port
  ## @param service.ports.https WordPress service HTTPS port
  ##
  # ports:
  #   http: 8080
  #   https: 8443
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: raspberrypi.local
