version: '3.1'

services:

  rtsp:
    image: mpromonet/v4l2rtspserver:latest
    restart: unless-stopped
    ports:
      - 554:8554
    command:
      - /dev/video0 
    devices:
      - /dev/video0
    deploy:
      resources:
        limits:
          memory: 1G
